#
# Config file for automatic testing at travis-ci.org
#
# build docker image and push it to docker hub.
#

language: bash
services: docker

before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
    - set -e

    # build 'jedie/pybee:latest'
    - cd base
    - ./build.sh

    # build
    - cd ..
    - ./build.sh

    - ./version_info.sh

    - cd tests
    - ./run_test.sh test_voc_turorial0.sh
    - ./run_test.sh test_helloworld.sh

after_script:
    - docker images

after_success:
    # push builded image to:
    # https://hub.docker.com/r/jedie/pybee/
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push jedie/pybee:latest;
      fi
