#
# Config file for automatic testing at travis-ci.org
#

language: bash
services: docker

before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
    - set -e
    - ./build.sh
    - ./version_info.sh

after_script:
    - docker images

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push jedie/pybee:latest;
      fi
