#
# Config file for automatic testing at travis-ci.org
#

language: bash
services: docker

before_script:
  - env | sort

script:
    # create docker image
    - ./build.sh

    # List all installed packages:
    - ./shell.sh pip freeze

    # Just print some version info:
    - ./shell.sh uname -a

    - ./shell.sh python --version
    - ./shell.sh javac -version
    - ./shell.sh ant -version
    - ./shell.sh node --version
    - ./shell.sh npm --version

    - ./shell.sh voc --version

after_script:
  - docker images

